/**
 * Regenerates `src/data/birthdays/us/colleges.csv` from Wikidata.
 *
 * The previous file was unusable: every row used `MM/DD/YYYY` in a single
 * column, which the parser reads as a bare `MM/DD` and silently discards the
 * year, and the years themselves were wrong (Alfred University was dated 2020
 * against an actual founding of 1836).
 *
 * Usage: bun run scripts/fetch-colleges.ts
 */

import fs from 'fs';
import path from 'path';
import { birthdayRows, sparql, toDatedItems } from './lib/wikidata.ts';

const OUTPUT = path.join(
	import.meta.dirname,
	'..',
	'src',
	'data',
	'birthdays',
	'us',
	'colleges.csv'
);

const QUERY = `SELECT DISTINCT ?item ?itemLabel ?date ?precision ?calendar WHERE {
	?item wdt:P31/wdt:P279* wd:Q38723 ;
	      wdt:P17 wd:Q30 .
	{ ?item p:P571/psv:P571 ?node } UNION { ?item p:P1619/psv:P1619 ?node }
	?node wikibase:timeValue ?date ;
	      wikibase:timePrecision ?precision ;
	      wikibase:timeCalendarModel ?calendar .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}`;

process.stdout.write('US higher-education institutions... ');
const bindings = await sparql(QUERY);
const items = toDatedItems(bindings);

// a handful of Wikidata labels are disambiguators rather than names
const named = items.filter(
	(item) => !(item.label.includes('(') && /\b(disambiguation|Q\d+)\b/.test(item.label))
);

const sorted = birthdayRows(named);
const header =
	'# generated by scripts/fetch-colleges.ts from Wikidata (P571 inception / P1619 official opening)\n' +
	'# day-precision dates only; dates before 1582 are as stated in the Julian calendar';

fs.writeFileSync(OUTPUT, `${header}\n${sorted.join('\n')}\n`);
process.stdout.write(`${bindings.length} raw -> ${items.length} dated -> ${sorted.length} rows\n`);
