/**
 * Generates `src/data/sports/founded.csv` from Wikidata inception dates for
 * leagues, governing bodies, halls of fame, motorsport series and circuits.
 *
 * Only founding dates come from here. Season windows and marquee event dates
 * live in the hand-maintained files, because they are scheduling conventions
 * rather than facts with a single structured source.
 *
 * Usage: bun run scripts/fetch-sports.ts
 */

import fs from 'fs';
import path from 'path';
import { birthdayRows, sparql, toDatedItems } from './lib/wikidata.ts';

const SPORTS_DIR = path.join(import.meta.dirname, '..', 'src', 'data', 'sports');

/**
 * Wikidata classes, split by the file each lands in. Matched with `P31`
 * directly; the `P279*` walk times out on the public endpoint. One-off event
 * editions ("2013 Summer Universiade") are deliberately excluded: their
 * inception is the date the event ran, not the birthday of anything.
 */
const GROUPS: Record<string, string[]> = {
	clubs: [
		'Q847017', // sports club
		'Q476028' // association football club
	],
	organizations: [
		'Q623109', // sports league
		'Q15991290', // professional sports league
		'Q4438121', // sports organization
		'Q2367225', // sports governing body
		'Q1079023', // hall of fame
		'Q1136508', // motorsport racing track
		'Q1777138', // racing circuit
		'Q10498148', // motorsport racing series
		'Q1478437', // auto racing series
		'Q13393265', // basketball league
		'Q15991303', // ice hockey league
		'Q15804850', // baseball league
		'Q15229207' // American football league
	]
};

/**
 * Builds the query for one class group.
 * @param classes - Wikidata class Q-ids
 * @returns SPARQL query text
 */
function query(classes: string[]): string {
	// the sport property is optional: several major leagues (NFL, NHL) omit it
	return `SELECT DISTINCT ?item ?itemLabel ?date ?precision ?calendar WHERE {
	VALUES ?class { ${classes.map((qid) => `wd:${qid}`).join(' ')} }
	?item wdt:P31 ?class ;
	      wikibase:sitelinks ?links .
	FILTER(?links >= ${classes.length > 5 ? 10 : 25})
	{ ?item p:P571/psv:P571 ?node } UNION { ?item p:P1619/psv:P1619 ?node }
	?node wikibase:timeValue ?date ;
	      wikibase:timePrecision ?precision ;
	      wikibase:timeCalendarModel ?calendar .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}`;
}

for (const [group, classes] of Object.entries(GROUPS)) {
	process.stdout.write(`sports ${group}... `);
	const bindings = await sparql(query(classes));
	const items = toDatedItems(bindings);

	const sorted = birthdayRows(items);
	const header =
		'# generated by scripts/fetch-sports.ts from Wikidata (P571 inception / P1619 official opening)\n' +
		`# ${group} with at least 25 Wikipedia sitelinks; day-precision dates only`;

	fs.mkdirSync(SPORTS_DIR, { recursive: true });
	fs.writeFileSync(path.join(SPORTS_DIR, `${group}.csv`), `${header}\n${sorted.join('\n')}\n`);
	process.stdout.write(
		`${bindings.length} raw -> ${items.length} dated -> ${sorted.length} rows\n`
	);

	await new Promise((resolve) => setTimeout(resolve, 1500));
}
