/**
 * Generates `src/data/anniversaries/space.csv` from Wikidata launch dates.
 *
 * Spaceflights carry `P619` (time of spacecraft launch), which is recorded to
 * the second, so unlike most inception dates the coverage here is near total.
 *
 * Usage: bun run scripts/fetch-space.ts
 */

import fs from 'fs';
import path from 'path';
import { csvField, sparql } from './lib/wikidata.ts';

const OUTPUT = path.join(import.meta.dirname, '..', 'src', 'data', 'anniversaries', 'space.csv');

/** Minimum Wikipedia sitelinks, as a proxy for "notable enough to be an anniversary". */
const MIN_SITELINKS = 30;

const QUERY = `SELECT DISTINCT ?item ?itemLabel ?launch ?links WHERE {
	?item wdt:P31/wdt:P279* wd:Q2133344 ;
	      wdt:P619 ?launch ;
	      wikibase:sitelinks ?links .
	FILTER(?links >= ${MIN_SITELINKS})
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}`;

process.stdout.write('spaceflights... ');
const bindings = await sparql(QUERY);

const today = new Date();

const byName = new Map<string, string>();
for (const row of bindings) {
	const label = row.itemLabel?.value?.trim();
	const launch = row.launch?.value;
	if (!label || !launch || /^Q\d+$/.test(label)) continue;

	const match = launch.match(/^(\d{4})-(\d{2})-(\d{2})T/);
	if (!match) continue;

	const [, year, month, day] = match as unknown as string[];
	if (month === '00' || day === '00') continue;

	// only flown missions are anniversaries; scheduled launch dates slip constantly
	if (new Date(`${year}-${month}-${day}T00:00:00Z`) > today) continue;

	const name = `${label} Launch`;
	if (!byName.has(name)) byName.set(name, `${csvField(name)},${month}/${day},${year}`);
}

const sorted = [...byName.entries()]
	.sort((a, b) => a[0].localeCompare(b[0], 'en'))
	.map(([, row]) => row);

const header =
	'# generated by scripts/fetch-space.ts from Wikidata (P619 time of spacecraft launch)\n' +
	`# spaceflights with at least ${MIN_SITELINKS} Wikipedia sitelinks`;

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, `${header}\n${sorted.join('\n')}\n`);
process.stdout.write(`${bindings.length} raw -> ${sorted.length} rows\n`);
