/**
 * Generates `src/data/sports/scheduled.csv`: events whose date follows a rule
 * the CSV schema cannot express, computed out over a range of years.
 *
 * The Indianapolis 500 and the Coca-Cola 600 run on the Sunday of Memorial Day
 * weekend, which is the Sunday immediately before the last Monday in May. That
 * is the fourth Sunday in most years and the fifth when May has five Sundays,
 * so neither `4SundayMay` nor `LSundayMay` is correct.
 *
 * Usage: bun run scripts/generate-sports-dates.ts
 */

import fs from 'fs';
import path from 'path';

const OUTPUT = path.join(import.meta.dirname, '..', 'src', 'data', 'sports', 'scheduled.csv');

const FIRST_YEAR = 2026;
const LAST_YEAR = 2040;

/**
 * Finds the last occurrence of a weekday in a month.
 * @param year - The year
 * @param month - The month (1-12)
 * @param dayOfWeek - Day of week (0-6, Sunday-Saturday)
 * @returns The date of the last such weekday
 */
function lastWeekdayOfMonth(year: number, month: number, dayOfWeek: number): Date {
	const lastDay = new Date(year, month, 0);
	const back = (lastDay.getDay() - dayOfWeek + 7) % 7;
	return new Date(year, month - 1, lastDay.getDate() - back);
}

/**
 * Memorial Day: the last Monday in May.
 * @param year - The year
 * @returns Memorial Day for that year
 */
function memorialDay(year: number): Date {
	return lastWeekdayOfMonth(year, 5, 1);
}

/**
 * The Sunday of Memorial Day weekend, i.e. the day before Memorial Day.
 * @param year - The year
 * @returns That Sunday
 */
function memorialDaySunday(year: number): Date {
	const sunday = memorialDay(year);
	sunday.setDate(sunday.getDate() - 1);
	return sunday;
}

/**
 * Formats a date as a local `YYYY-MM-DD`.
 * @param date - The date
 * @returns The ISO calendar day
 */
function iso(date: Date): string {
	return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
}

const rows: string[] = [];
for (let year = FIRST_YEAR; year <= LAST_YEAR; year++) {
	const sunday = memorialDaySunday(year);
	rows.push(`Indianapolis 500 ${year},${iso(sunday)}`);
	rows.push(`Coca-Cola 600 ${year},${iso(sunday)}`);
}

const header = [
	'# generated by scripts/generate-sports-dates.ts',
	'# events whose date follows a rule the CSV schema cannot express',
	'# Indianapolis 500 and Coca-Cola 600 run on the Sunday before Memorial Day (the last Monday in May)'
].join('\n');

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, `${header}\n${rows.sort().join('\n')}\n`);
process.stdout.write(`sports/scheduled.csv: ${rows.length} rows\n`);
